export type CartErrorCode =
  | "CART_NOT_FOUND"
  | "ROOM_NOT_FOUND"
  | "MEMBER_NOT_FOUND"
  | "RESERVATION_NOT_FOUND"
  | "RESERVATION_NOT_IN_CART"
  | "EXCEEDS_MAX_GUESTS"
  | "DUPLICATE_RESERVATION"
  | "RESERVATION_NOT_PENDING"
  | "RESERVATION_NOT_BELONGS_TO_USER"
  | "INVALID_CHECKOUT_DATE"
  | "CONFLICTING_RESERVATION"
  | "RESERVATION_MISMATCH";
