export const CategoryData = [
  { id: 1, categoryName: "전국" },
  { id: 2, categoryName: "서울" },
  { id: 3, categoryName: "인천" },
  { id: 4, categoryName: "대전" },
  { id: 5, categoryName: "대구" },
  { id: 6, categoryName: "광주" },
  { id: 7, categoryName: "부산" },
  { id: 8, categoryName: "울산" },
  { id: 9, categoryName: "세종특별자치시" },
  { id: 10, categoryName: "경기도" },
  { id: 11, categoryName: "강원특별자치도" },
  { id: 12, categoryName: "충청북도" },
  { id: 13, categoryName: "충청남도" },
  { id: 14, categoryName: "경상북도" },
  { id: 15, categoryName: "경상남도" },
  { id: 16, categoryName: "전북특별자치도" },
  { id: 17, categoryName: "전라남도" },
  { id: 18, categoryName: "제주도" },
] as const;
