export const CATEGORY_DATA = [
  { id: 1, categoryName: "서울" },
  { id: 2, categoryName: "부산" },
  { id: 3, categoryName: "대구" },
  { id: 4, categoryName: "인천" },
  { id: 5, categoryName: "대전" },
  { id: 6, categoryName: "광주" },
  { id: 7, categoryName: "울산" },
  { id: 8, categoryName: "세종" },
  { id: 9, categoryName: "경기" },
  { id: 10, categoryName: "강원" },
  { id: 11, categoryName: "충북" },
  { id: 12, categoryName: "충남" },
  { id: 13, categoryName: "전북" },
  { id: 14, categoryName: "전남" },
  { id: 15, categoryName: "경북" },
  { id: 16, categoryName: "경남" },
  { id: 17, categoryName: "제주" },
] as const;
