export type ReservationErrorCode =
  | "RESERVATION_NOT_FOUND"
  | "NO_ROOMS_AVAILABLE"
  | "MEMBER_NOT_FOUND"
  | "OVERLAPPING_RESERVATION"
  | "ROOM_NOT_FOUND"
  | "EXCEEDS_MAX_GUESTS"
  | "INVALID_CHECKOUT_DATE"
  | "CONFLICTING_RESERVATION"
  | "DUPLICATED_RESERVATION";
