export type AuthErrorCode =
  | "EMAIL_ALREADY_EXISTS"
  | "NICKNAME_ALREADY_EXISTS"
  | "USER_NOT_FOUND"
  | "AUTHENTICATION_FAILED"
  | "PASSWORD_MISMATCH"
  | "INVALID_REFRESH_TOKEN"
  | "INVALID_TOKEN"
  | "INVALID_ACCESS_TOKEN"
  | "BLACKLISTED_TOKEN"
  | "REFRESH_TOKEN_NOT_FOUND"
  | "TOKEN_FETCH_FAILED";
